name: Validate renovate configuration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v2.1.0
        with:
          config-file_path: default.json
